### PR TITLE
fix issues with running bg-merger twice and add more functionalities

### PR DESCRIPTION
**Pull request by raffaelladevita**
* address #373 
* new functionalities:
  * accept a list of bg files
  * loop over the same bg file
  * merge multiple events to increase bg level
  * save bg-removed bg events
  * allow the selection of specific DC regions for merging

### CODE REVIEW

**Comment by baltzell** [comment]
Did we lose the error return value in the engine's init?

**Comment by baltzell** [comment]
Let's make sure the default settings, e.g., which detectors are enabled, are what most people should want (and what should be used on OSG).

**Comment by raffaelladevita** [comment]
> Let's make sure the default settings, e.g., which detectors are enabled, are what most people should want (and what should be used on OSG).

done

**Comment by raffaelladevita** [comment]
> Did we lose the error return value in the engine's init?

The error is now returned by the setgFiles method

**Comment by baltzell** [comment]
Is engine's init always returning good now?

**Comment by raffaelladevita** [comment]
No, it’s returning false if any of the input files doesn’t exist or is unreadable or…as before

**Review by baltzell — APPROVED** [review]

**Pull request merged**
