### PR TITLE
ci: run tests on `darwin`

### LINKED ISSUE #119: Add `darwin` build testing to CI
If we want to maintain support for `darwin` (Mac), we should be testing it.

(cf. #118)

### PR DESCRIPTION
**Pull request by c-dilks**
close #119 
- builds on both Ubuntu and MacOS
- runs only one test on MacOS because of [concurrency limits for MacOS runners](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration)

### CODE REVIEW

**Comment by c-dilks** [comment]
As expected, the `macos-latest` tests are failing because of #118.

EDIT: which is currently version 12, though runners with version 13 are also available.

**Comment by c-dilks** [comment]
This PR is still a draft, please don't rebase. I wanted to test another type of failure mode before opening.

**Comment by c-dilks** [comment]
This is not the conflict resolution I wanted to test on the CI.

**Comment by c-dilks** [comment]
Please don't push another commit, I want to watch the current pipeline to make sure the build job fails correctly.

**Comment by c-dilks** [comment]
All right, the `realpath` error was successfully caught (previously it was being ignored, even after #122), as shown in https://github.com/JeffersonLab/coatjava/actions/runs/6356404731/job/17265949654?pr=121#step:4:8

Let's just include the fix with this PR, since we don't do squash merging here: https://github.com/JeffersonLab/coatjava/pull/121/commits/3ee5580226a80683c71b5be43982717abf4a7c6e

**Comment by c-dilks** [comment]
[Successful pipeline](https://github.com/JeffersonLab/coatjava/actions/runs/6356448734), this PR is now ready.

**Comment by c-dilks** [comment]
Github limits the max number of concurrent MacOS runner jobs more than the Ubuntu runners, so let's limit the test matrix to one job for MacOS.

**Comment by c-dilks** [comment]
Ready!

**Review by baltzell — APPROVED** [review]

**Pull request merged**
