### PR TITLE
Revised the name of the hit bank in AHDCengine.java

### PR DESCRIPTION
**Pull request by efuchey**
Revised the name of the hit bank in AHDCengine.java

### CODE REVIEW

**Comment by whit2333** [comment]
Please merge ASAP

**Comment by baltzell** [comment]
Sounds like this change is supposed to make it consistent with what's coming out of GEMC currently?

**Comment by whit2333** [comment]
There are related PRs:
https://github.com/gemc/clas12Tags/pull/11
https://github.com/gemc/source/pull/232

**Comment by c-dilks** [comment]
Ignore the deployment errors (CI issue, fixed upstream).

**Comment by c-dilks** [comment]
It doesn't look like this PR changes anything anymore, or perhaps your proposed changes are already upstream. Closing, but please re-open if you still need this.

**Pull request closed without merging**
