### PR TITLE
Added ALERT detector types

### LINKED ISSUE #273: ALERT is missing DetectorTypes

### PR DESCRIPTION
**Pull request by whit2333**
- ATOF and AHDC

### CODE REVIEW

**Review by baltzell — DISMISSED** [review]

**Comment by whit2333** [comment]
@baltzell Can you merge this?

**Review by raffaelladevita — CHANGES_REQUESTED** [review]
It's not a strict requirement but we have been following the convention of assigning the hipo banks group for a given detector based on the DetectorType value, e.g. URWELL DetectorType is 23 and URWELL::adc has group 2**23**00.

Since AHDC and ATOF banks have already been defined in gemc with group set to 22400 and 22500, respectively, DetectorType values for the two detectors should be swapped.

**Review by whit2333 — COMMENTED** [review]
thanks

**Comment by whit2333** [comment]
I am going to include these changes in the ATOF Decoder PR.

**Pull request closed without merging**
